### ISSUE TITLE
[BUG] If there are more than 100,000 photos on the iPhone, the loading takes too long.

### ISSUE THREAD

**Issue by myeongseop-sofit** [fluttercandies/flutter_wechat_assets_picker#387]
**Describe the bug**

If there are more than 100,000 photos on the iPhone, the loading takes too long.

1. Recent loading takes a long time.
2. It takes a long time to load the picture.

The iPhone seems to load all the pictures by reversing the alignment of the photos.
Can't you arrange the pictures upside down and load the latest ones first?

**How to reproduce**
```
final result = await AssetPicker.pickAssets(
        context,
        pickerConfig: AssetPickerConfig(
          pageSize: 30,
          gridCount: 3,
          maxAssets: 5,
          requestType: RequestType.image,
          textDelegate: KoAssetPickerTextDelegate(),
          loadingIndicatorBuilder: (BuildContext context, bool isAssetsEmpty) {
            return const Center(
              child: CupertinoActivityIndicator(),
            );
          },
          selectPredicate: (context, asset, isSelected) async {
           ...
          specialItemPosition: SpecialItemPosition.prepend,
          specialItemBuilder: (context, path, length) {
...
```

**movie**
https://www.youtube.com/shorts/GmLlM-nCu0I

**Version information**

Device: iPhone 13 Pro
OS: iOS 16.1.1
Package Version: 8.1.4
Flutter Version: 3.3.8

**Comment by myeongseop-sofit** [comment]
It took 35 seconds for the pictures to load.

**Comment by AlexV525** [comment]
Please take another screen recording using the example with minimum argument updates in the repo rather than a production app. Also, are 100,000 photos all locally available or all cloud-stored?

From the recording you've provided, it seems the request for the assets list is blocking the layout process. cc @CaiJingLong

> The iPhone seems to load all the pictures by reversing the alignment of the photos. Can't you arrange the pictures upside down and load the latest ones first?

It would be more appropriate if you can ask politely. If you ever see the code, you'll understand how the grid revert and how assets placing in the grid.
