### ISSUE TITLE
[Feature] Dialogues behavior handle

### ISSUE THREAD

**Issue by SchnMar** [fluttercandies/flutter_wechat_assets_picker#63]
Hi Alex,

I have another request/question.

**Version information (版本信息)**
 - OS:  iOS 13.7

**Describe the solution you'd like (描述你期望的解决方案)**
I use the Assets Picker to upload images to a social media app I developed myself (not yet released). Now I want to edit a post and I want to give the user the possibility to also edit the already uploaded images. I tried to use the described implementation from the documentation with saving the images locally and deleting them after the user has completed editing his post (https://github.com/fluttercandies/flutter_wechat_assets_picker#create-assetentity-from-file-or-uint8list-rawdata). 
Unfortunately, ```PhotoManager.editor.deleteWithIds``` causes a dialogue to appear to the user that temporarily saved images are deleted, which I don't want to appear as it is confusing to the user.

I have thought about the following solution:
- keeping images in memory (as UInt8List) and make them appear in the AssetPicker in recent path as first images or have a special section?

What do you think?
Thank you again for your great work!
Marcel

**Comment by AlexV525** [comment]
I think there is a way to save image locally and get a `AssetEntity` without further dialogs confirmation.

@CaiJingLong Are you still remember the solution?

**Comment by CaiJingLong** [comment]
1. AssetEntity is to describe the entity in the system album.
2. The dialog box is a system behavior and cannot be interfered.

I suggest you wrap AssetEntity by yourself, and use the wrapped class to describe your resources, so that "virtual" behavior simulates AssetEntity.

PhotoManager only helps you process album resources, and you should not be responsible for your project-specific business activities.

**Comment by AlexV525** [comment]
Closing without response.
